[[servers]]

host = "service-auth-ldap.marathon.l4lb.thisdcos.directory"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false

bind_dn = "cn=${LDAP_USER},dc=coldis,dc=org"
bind_password = '${LDAP_PASSWORD}'

search_filter = "(cn=%s)"
search_base_dns = ["ou=users,dc=coldis,dc=org"]

group_search_filter = "(&(objectClass=posixGroup)(memberUid=%s))"
group_search_filter_user_attribute = "uid"
group_search_base_dns = ["ou=groups,dc=coldis,dc=org"]

[[servers.group_mappings]]
group_dn = "cn=administrators,ou=technology,ou=groups,dc=coldis,dc=org"
org_role = "Admin"
grafana_admin = true

[[servers.group_mappings]]
group_dn = "cn=directors,ou=groups,dc=coldis,dc=org"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "cn=data-scientists,ou=data,ou=groups,dc=coldis,dc=org"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "cn=developers,ou=technology,ou=groups,dc=coldis,dc=org"
org_role = "Editor"

[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
email =  "email"
